include:
  - board: nice_nano_v2
    shield: corne_left
    keymap: corne
    cmake-args: >
      -DZMK_SPLIT_ROLE=left
      -DDTC_OVERLAY_FILE=$GITHUB_WORKSPACE/config/boards/shields/corne/corne_left.overlay
