name: Build ZMK (corne_nice on nice_nano_v2)

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
    with:
      config_path: config
      archive_name: LeKramer
      # IMPORTANT: valid JSON array, fully closed, no trailing commas.
      build_matrix: |
        [
          { "board": "nice_nano_v2", "shield": "corne_nice", "keymap": "corne", "cmake-args": "-DZMK_SPLIT_ROLE=left"  },
          { "board": "nice_nano_v2", "shield": "corne_nice", "keymap": "corne", "cmake-args": "-DZMK_SPLIT_ROLE=right" }
        ]
